### ISSUE TITLE
Determine acceptable number of indexing requests per minute

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/dor_indexing_app#90]
According to NewRelic, we're currently handling approximately (2 services) * (60 requests per minute). What should our target be?

**Comment by drh-stanford** [comment]
also what should our latency target be for time per request?

this is related to #59.

**Comment by drh-stanford** [comment]
talked about this issue in standup. we have a few outstanding questions and will discuss early next week:

- what is the minimum throughput required? and the target throughput?
- what is the maximum time an indexing request should take? and the minimally acceptable time?
- what is the expected maximum size of an indexing batch (a collection?) that would need to be reindexed? and how long should that take?
- what are the bounds on the backlog size?


we also discussed that monitoring activity is difficult because a completely idle state isn't necessarily an error (e.g., winter closure).

**Comment by cbeer** [comment]
I'd add:

- what is the maximum time a complete reindex should take?
- most collections have < 100 items; if we remediate a collection, how long should reindex that take?

**Comment by cbeer** [comment]
Right now, a full reindex would take about a week, and a 100 item collection would take about a couple minutes.

**Comment by jmartin-sul** [comment]
using the argo bulk reindexing workers, a full reindex on just over a million objects took just over four days.  i think we would've preferred something closer to a day or two at most, but we found that tolerable.

@blalbrit probably has a better idea of what kind of throughput we'd need to keep people from feeling like indexing was slowing their work down.

**Comment by cbeer** [comment]
@blalbrit says we'd like to be able to do a complete reindex in 3 days.

**Comment by cbeer** [comment]
@drh-stanford: you did some math on this, right? Something like 250 - 300 requests per minute?

**Comment by drh-stanford** [comment]
The argo3 production core has 1.2M objects. So, 3 days is ~275 rpm sustained.

**Comment by drh-stanford** [comment]
I update the wiki for the targets.
