### ISSUE TITLE
ModelNotAsserted failures for DOR objects without identityMetadata

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/dor_indexing_app#93]
Some DOR objects are lacking `identityMetadata`. For example, https://argo.stanford.edu/catalog/druid:wz924gg6479 is missing the `identityMetadata` datastream but has RELS-EXT:

```xml
  <rdf:Description rdf:about="info:fedora/druid:wz924gg6479">
    <fedora-model:hasModel rdf:resource="info:fedora/afmodel:Etd"/>
    <hydra:isGovernedBy rdf:resource="info:fedora/druid:bx911tp9024"/>
  </rdf:Description>
```

Maybe we need to default to an `objectType` of `item` when there's no identityMetadata available?

See Honeybadger https://app.honeybadger.io/projects/49898/faults/31701552#notice-summary

**Comment by LynnMcRae** [comment]
I believe this is one of a handful of damaged ETDs from 2012 that got through submission incomplete though I don't know if they all lack identityMetadata. Is the error from lack of identityMetadata or lac of objectType specifically. We know that all the ETD "part" objects (afmodel:Part) lack identityMetadata and therefore objectType. Aside from those, there are 19 objects in DOR with no declared objectType according to the Empty Fields facet. I will review and repair what I can.

**Comment by cbeer** [comment]
`Dor.find` used to fall back to `Dor::Item`, so I don't see the harm in adding that again.. although fixing the data seems like generally good practice.

**Comment by LynnMcRae** [comment]
This Model error -- ActiveFedora::ModelNotAsserted: Unable to adapt #<Dor::Abstract pid: "druid:wz924gg6479"> to a model asserted for the resource.

... is about an ETD "part" object. This model was one of our first alongside Google Scanned Books.  It was also our experiment in the fedora "atomistic" model which made baby objects for each file, an approach we quickly abandoned. Unfortunately we never redid the app to do anything else so these are still being made. Since I'm pretty sure a new ETD release is not in the cards, I think assuming a missing objectType is an "item" is a safe bet for these objects.
