### ISSUE TITLE
Simplify generate_dublin_core

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/dor_indexing_app#97]
We're both using the Stanford MODS gem and an XSLT stylesheet to generate the dublin core index fields. We can simplify this code by solely using the MODS gem, and it'll improve the performance somewhat as we won't need to parse and transform via XSLT.

**Comment by cbeer** [comment]
I started looking into this, and I think our first step needs to be to define what metadata we expect to extract from the MODS and how it is used. There are some significant differences between the XSLT mapping and mods/stanford-mods, but probably have no real-world impact.

**Comment by LynnMcRae** [comment]
It would be a contradiction to generate any dc_ or public_dc_ solr fields directly from MODS. They should only exist as reflections of the MODS to DC transformation done via the LoC XSLT.  The question is whether we need to do this at all.  The index needs the basic set of bibliographic description -- titles, authors, contributors, subjects, notes, abstract -- as keyword fodder if nothing else (lacking advance search). We should be able to get this from one source.  The DC reduction of this into its buckets was likely attractive because it would have smoothed out differences between differing forms of descMetadata, but going to both places would be redundant. 

In case it's not clear, the MODS-to-DC service exists principally for publish because we put a full copy of Dublin Core into the Public XML. It is what it is as supported by the Library of Congress, and we don't really want to be in there futzing with it, and not rely on it much beyond a published artifact.

**Comment by blalbrit** [comment]
@LynnMcRae Agree completely that no change to MODS-to-DC service for publish. For use within Argo (and within the DOR index), I see no reason at all to rely on the DC. Unless I'm missing something, the proposal here is to simplify the indexing logic by getting the bag of keyword terms from MODS only instead of across datastreams.
